### ISSUE TITLE
System.ComponentModel.EditorBrowsable特性重复

### ISSUE THREAD

**Issue by gailium119** [dotnet-campus/dotnetCampus.Ipc#105]
如题，编译项目出现此问题，如何解决

**Comment by gailium119** [comment]
已发现问题触发条件，在wpf项目中使用IpcPublic就会触发，除非没用任何xaml文件。但wpf为项目需要，能否解决

**Comment by lindexi** [comment]
@gailium119 更新你的 VS 试试，因为 IpcPublic 使用了 SourceGenerator 技术，这个技术在旧版本的 dotnet sdk 存在 bug 导致了重复引用。也许你升级版本就能解决

**Comment by gailium119** [comment]
我用的vs2022+.Net 6.0.8

**Comment by lindexi** [comment]
@gailium119 重试了几次，没能复现，方便你的项目代码贴出来？

**Comment by lindexi** [comment]
也许和 https://github.com/dotnet/wpf/issues/6792 相关，但是记得这个问题已修复

**Comment by lindexi** [comment]
@gailium119 要不，你在 csproj 上加上以下代码试试

```xml
<Target Name="_WPFIssue6792_RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
		<!-- Work around https://github.com/dotnet/wpf/issues/6792, remove for .NET 6.0.500 or later -->

		<ItemGroup>
			<FilteredAnalyzer Include="@(Analyzer-&gt;Distinct())" />
			<Analyzer Remove="@(Analyzer)" />
			<Analyzer Include="@(FilteredAnalyzer)" />
		</ItemGroup>
	</Target>
```

**Comment by walterlv** [comment]
@gailium 大约在你提出这个问题的前后数周，我们团队里面每个人都遇到了类型/特性重复的问题。后面 .NET SDK / Visual Studio 升级后问题就解决了。
