### ISSUE TITLE
System.NotSupportedException -->vs2022 preview17.5,   .net framework4.8

### ISSUE THREAD

**Issue by yiszza** [dotnet-campus/dotnetCampus.Ipc#111]
System.NotSupportedException:“因为编译时没有生成“IFoo”接口的 IPC 代理与对接类，所以运行时无法创建他们的实例。请确保使用 Visual Studio 2022 或以上版本、MSBuild 17 或以上版本进行编译。”

**Comment by lindexi** [comment]
@yiszza 这里用到源代码生成技术，可能是你的 VS 抽了一下
