### ISSUE TITLE
The overload method with same amount of argument 

### ISSUE THREAD

**Issue by afunc233** [dotnet-campus/dotnetCampus.Ipc#116]
version 2.0.0-alpha213

![image](https://user-images.githubusercontent.com/19919631/217241640-2e3df339-17f0-480b-a04b-af40e2894dab.png)

**Comment by lindexi** [comment]
@afunc233 原本的定义代码或者是比较简单的复现项目贴上来可好

**Comment by afunc233** [comment]
```
[IpcPublic]
interface IMainIpc
{
    int Add(int a, int b);
    long Add(long a, long b);
}
```

@lindexi haha

**Comment by walterlv** [comment]
![image](https://user-images.githubusercontent.com/9959623/217411305-a27f0265-5688-4c70-9991-06dcfd2c5f1f.png)

我们在单元测试里增加了 @afunc233 所提供的用例，现在正在着手解决这个问题。特别感谢！

**Comment by walterlv** [comment]
@afunc233 经过调查，原因如下：

1. 我们在 IPC 内部收发消息时使用字典 `Dictionary` 来保存方法调用与对应的发送代理之间的关系；
2. 字典中，我们仅使用了方法名和参数个数作为键（Key），所以如果 `IpcPublic` 接口中存在参数个数相同的重载方法，那么就会发生混淆（在您的例子中，是抛出了异常）

如果希望 Ipc 库能识别相同参数个数的重载，就需要在键（Key）中加入参数类型。但由于参数个数不确定，所以这样的字典键（Key）很难构造出来。因此我们决定：

* 在我们找到合适的方案解决这个问题之前，会在 `IpcPublic` 接口中发现参数个数相同的重载方法时，给出编译错误报告，提示修改方法名。

@afunc233 如果你有更好的方法，欢迎提供你的建议！感谢！

**Comment by afunc233** [comment]
字典中的key 如果使用 System.Reflection.MethodBase.GetCurrentMethod().ToString() 是否可行？

**Comment by lindexi** [comment]
@afunc233 那接收端就找不到了

**Comment by afunc233** [comment]
按道理如果把这个key 也发送到接收端 应该还是可以找到的吧  我再看下

**Comment by lindexi** [comment]
@afunc233 接收端收到这个Key之后不知道调用哪个对应的方法

**Comment by afunc233** [comment]
System.Reflection.MethodBase.GetCurrentMethod().ToString()  这个应该可以算作 方法签名的吧  接收端 直接找相同的方法签名 进行调用 按说是可行 ，我还没有深入的看代码 可能理解的不对

**Comment by lindexi** [comment]
@afunc233 考虑到接收端是放在另一个进程里面去了，可能程序集都不相同，因此这个方法应该是难以实现的

**Comment by afunc233** [comment]
后面有时间的话 我研究一下库

**Comment by walterlv** [comment]
@afunc233 现在，我们在生成代理和对接的时候，为方法签名生成了一段唯一的 Id，通信的时候使用此唯一 Id 作为标识符。所以问题已经解决了。你应该马上就能使用到解决问题的版本了。

阅读了你们俩的对话，发现你（@afunc233）的方法是可行的，至少在大多数情况下都是。唯一的小问题就是使用此 IPC 库做的软件可能存在跨版本兼容性问题，即如果开发者修改了接口中某个方法参数的名称，那么 IPC 调用时将无法与修改前编译的软件进行通信（而正常 .NET 调用是允许的）。当然，基于你的方法改进也很容易，不使用 `ToString()` 而是把参数类型都取出来即可。现在我的改动也是这样，只是额外将此字符串生成了一段唯一 Id。

**Comment by afunc233** [comment]
@walterlv  @lindexi 感谢两位大佬

**Comment by afunc233** [comment]
另 如方法

`string Add(int A, int B)`

它的 System.Reflection.MethodBase.GetCurrentMethod().ToString()  的值为 System.String Add(Int32, Int32)  所以如果仅修改某参数的名称的话 按说是不会找不到 对应方法 进行调用， 在我看来 生成的ID 跟 直接  `ToString()` 没有明显差异  不过目前我并不知道本库的处理细节 所以仅是猜想 后续有空研究的时候 再证实的我想法

**Comment by walterlv** [comment]
@afunc233 你说的是对的，`ToString()` 与 ID 没有本质上的差异，甚至可以说没有任何区别。

只是 `System.Reflection.MethodBase.GetCurrentMethod().ToString()` 是使用反射技术，而本库使用的是编译器技术，无法在此上下文中使用反射。当然编译器技术也可以拼接出与反射技术完全相同的字符串。

唯一的问题就是此字符串可能会很长（尤其是在参数列表比较多的时候，各参数需要类型全名时会浪费大量的字符串），在 IPC 传输中会大量浪费带宽。
