### ISSUE TITLE
如果调用函数中传入参数类型为接口类型，远程调用端返回为null

### ISSUE THREAD

**Issue by guanguanchuangyu** [dotnet-campus/dotnetCampus.Ipc#154]
![image](https://github.com/user-attachments/assets/7671153b-1901-4f6b-ab8f-2323025e79bc)
核对代码后，初步判定是JsonIpcMessageSerializer.cs反序列化不支持interface，在实际使用是否遇到过类似场景？

**Comment by lindexi** [comment]
@guanguanchuangyu 会有这样的情况，取决于序列化是否成功。有更多的项目代码没？有的话可以帮你测试一下在你的业务情况下的行为

**Comment by walterlv** [comment]
对于你列出的这个方法，调用方很容易传入某个接口的实现，不过被调用方就很难给出一个此接口的实现了。所以这种情况，我认为应该直接在编译时报告错误，不支持传入除 IPC 接口之外的其他接口。

不知道两位怎么看？@guanguanchuangyu @lindexi

**Comment by lindexi** [comment]
@walterlv 如果构建时候能判断出来，那是更好的

**Comment by guanguanchuangyu** [comment]
@lindexi 我整理一下，有一个简单案例，出问题的话，基本都是返回类型和传入类型为接口类型。
[WPFCampusIpc.zip](https://github.com/user-attachments/files/16238772/WPFCampusIpc.zip)

**Comment by walterlv** [comment]
@guanguanchuangyu 试了下你的 demo。为了使其正常工作，我把 IClass1 和 IResult 都标上了 [IpcPublic] 后，IPC 行为已经正常了。

原因是：
- 目前 IPC 库会对所有标记了 IpcPublic 的接口生成代理类（也就是你提到的类似 mock 的自定义手段），这时无论是在 IPC 参数还是返回值中，这种类型都会自动使用代理类进行 IPC 通信，可以正常工作
- 截至目前，没有标记 IpcPublic 的接口都没有做任何其他处理

对于你的项目场景：
- 假如允许在接口上增加此 IpcPublic 特性，建议为其加上，以为其生成代理类
- 假如不允许在接口上增加此特性，可考虑写一个空的子接口继承自那个接口，在子接口上标记 IpcPublic；然后再修改这个主 IPC 接口中的参数和返回值使其使用子接口（相信这个主 IPC 接口你是能动的，因为你已经在这个接口上加上了 IpcPublic 特性

额外的：
- 我们（和 @lindexi）计划讨论下是否允许没有被标记为 IpcPublic 的接口参与到 IPC 的参数或返回值中来。目前初步来看，这并不可行，因为如果允许隐式接口 IPC 通信（目前是显式，必须标记），那么必须从一个 IpcPublic 类开始，递归地搜寻所有涉及到的接口（此过程还可能涉及到循环引用），对代理类的生成是个不小的挑战。
- 当然，一定会做的事情是，一旦我们确定方案，我们会增加一个分析器帮助写出正确的代码（对于此例，要么是禁止传递未标记 IpcPublic 的接口，要么是提示开发者为参数或返回值的接口添加 IpcPublic 特性）。

以下，是对你的项目 IClass1 和 IResult 增加 IpcPublic 特性后正常工作的截图：

![image](https://github.com/user-attachments/assets/e64b3e45-d07f-40a2-ac9c-8d68823e8adf)

**Comment by guanguanchuangyu** [comment]
感谢！感谢！明白了，如果需要参与传输，那就需要添加特性。问题可以解决。那这个issue我关闭了。

> @guanguanchuangyu 试了下你的 demo。为了使其正常工作，我把 IClass1 和 IResult 都标上了 [IpcPublic] 后，IPC 行为已经正常了。
> 
> 原因是：
> 
> * 目前 IPC 库会对所有标记了 IpcPublic 的接口生成代理类（也就是你提到的类似 mock 的自定义手段），这时无论是在 IPC 参数还是返回值中，这种类型都会自动使用代理类进行 IPC 通信，可以正常工作
> * 截至目前，没有标记 IpcPublic 的接口都没有做任何其他处理
> 
> 对于你的项目场景：
> 
> * 假如允许在接口上增加此 IpcPublic 特性，建议为其加上，以为其生成代理类
> * 假如不允许在接口上增加此特性，可考虑写一个空的子接口继承自那个接口，在子接口上标记 IpcPublic；然后再修改这个主 IPC 接口中的参数和返回值使其使用子接口（相信这个主 IPC 接口你是能动的，因为你已经在这个接口上加上了 IpcPublic 特性
> 
> 额外的：
> 
> * 我们（和 @lindexi）计划讨论下是否允许没有被标记为 IpcPublic 的接口参与到 IPC 的参数或返回值中来。目前初步来看，这并不可行，因为如果允许隐式接口 IPC 通信（目前是显式，必须标记），那么必须从一个 IpcPublic 类开始，递归地搜寻所有涉及到的接口（此过程还可能涉及到循环引用），对代理类的生成是个不小的挑战。
> * 当然，一定会做的事情是，一旦我们确定方案，我们会增加一个分析器帮助写出正确的代码（对于此例，要么是禁止传递未标记 IpcPublic 的接口，要么是提示开发者为参数或返回值的接口添加 IpcPublic 特性）。
> 
> 以下，是对你的项目 IClass1 和 IResult 增加 IpcPublic 特性后正常工作的截图：
> 
> ![image](https://private-user-images.githubusercontent.com/9959623/348894018-e64b3e45-d07f-40a2-ac9c-8d68823e8adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDMxNTksIm5iZiI6MTcyMTEwMjg1OSwicGF0aCI6Ii85OTU5NjIzLzM0ODg5NDAxOC1lNjRiM2U0NS1kMDdmLTQwYTItYWM5Yy04ZDY4ODIzZThhZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDQwNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgxODQzODRmZGRhMWM2ODYxOWVkOWUxZGJmMTkwY2E2YjcyYTBlOWNjY2JlYjczYjFmYmNiZjczYWJmMjZlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nq4r3Fkg6ykf0nyLw7oJ8B18BS0klm5iiaKm0KECFIM)
