### ISSUE TITLE
IpcShapeGenerator processes every syntax tree in the compilation with every call to Execute

### ISSUE THREAD

**Issue by sharwell** [dotnet-campus/dotnetCampus.Ipc#97]
The following code does not use the new `IIncrementalGenerator` API, which leads to severe performance overhead when attempting to enable the source generator in IDE scenarios.

https://github.com/dotnet-campus/dotnetCampus.Ipc/blob/d8b94a050a138b274b287b5e7e76409ac2dfb88b/src/dotnetCampus.Ipc.Analyzers/SourceGenerators/IpcShapeGenerator.cs#L75-L84

🔗 This issue was originally reported here: https://developercommunity.visualstudio.com/t/Visual-Studio-hangs-and-can-not-cancal-t/10047643

**Comment by lindexi** [comment]
@sharwell Thank you and we will fix it

**Comment by walterlv** [comment]
Related documents:

* [roslyn/incremental-generators.md at main · dotnet/roslyn](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md)
